component_depth: 1
languages:
  - name: python
    production:
      exclude:
        - /muscle_manager_protocol/.*\.py
        - /scripts/.*\.py
        - /setup.py
        - /docs/.*
        - .*/test/.*\.py
    test:
      include:
        - .*/test/.*\.py
        - /integration_test/.*\.py
  - name: cpp
    production:
      exclude:
        - /libmuscle/cpp/src/muscle_manager_protocol/.*
        - /libmuscle/cpp/src/libmuscle/bindings/.*
        - /libmuscle/cpp/src/ymmsl/bindings/.*
        - .*/tests/.*\.?pp
        - /docs/.*
    test:
      include:
        - .*/tests/.*\.?pp
